<div style="width: 40%; clear: both;">
<div style="float: left; width: 20%;">
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f7/Universidad_T%C3%A9cnica_Patricular_de_Loja.png", align="left" width="280" height="120">
</div>
</div>
<div style="float: right; width: 70%;">
<p style="margin: 0; padding-top: 32px; text-align:right; color:#003366; font-size:16px"><u>Análisis de datos y visualización</u></p>
<p style="margin: 0; text-align:right; color:#999999; font-size:17px">Maestría en Inteligencia Artificial Aplicada</p>
</div>
</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>


# Estructuras de datos: arrays, diccionarios, series y dataframes

## Carga de librerías base

In [2]:
import numpy as np
import pandas as pd

## 1. Creación de arrays con Numpy

In [3]:
# Creación de array de una dimensión desde lista:
list1D = [3, 2, 5, 8, 4, 9, 7]
print(type(list1D), list1D)

npArray = np.array(list1D)
print(type(npArray), npArray)

# Creación directa
print(np.array([1, 0, 0, 1], dtype=bool))

<class 'list'> [3, 2, 5, 8, 4, 9, 7]
<class 'numpy.ndarray'> [3 2 5 8 4 9 7]
[ True False False  True]

In [4]:
#Creación de array de 2 dimensiones desde lista:

list2D = [[1,2,3,4],
        [5,6,7,8], 
        [9,0,10,11]]

npArray = np.array(list2D)

print(type(npArray), npArray)

<class 'numpy.ndarray'> [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0 10 11]]

### Diferencias entre objetos de tipo list y array
    
- Una lista puede contener diferentes datos de diferentes tipos.
- Un array de numpy solo puede contener datos del misto tipo.
    
Cuando enviamos diferentes tipos de datos ocurre una conversión automática.

In [5]:
# Conversión automática de tipos de datos:
listD = [1, 'casa', True, 1.5]
arrayD = np.array(listD); print(arrayD)

listD = [1, 7.8, True ,1.5]
arrayD = np.array(listD); print(arrayD)

['1' 'casa' 'True' '1.5']
[1.  7.8 1.  1.5]

### Funciones para crear arrays desde 0

In [6]:
print(np.zeros(10)) # array de 10 ceros.

print(np.random.random(10)) # array de números aleatorios

print(np.arange(10)) # array de los primeros 10 números, incluído el 0

# Para crear arreglos de más de una dimensión se deben enviar las dimensiones:
print(np.zeros((3, 2))) # array de ceros de dimensión 3x2.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.31802089 0.21262529 0.04494425 0.86624542 0.77598345 0.52421381
 0.70009208 0.45022103 0.07149097 0.28352021]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]]

### Dimensión y tipos de datos

In [8]:
print(len(list2D)) # lista

print(len(npArray)) # arreglo

print(npArray.shape) # arreglo de dos dimensiones

# Tipos de datos:

print(type(list2D)) # para lista
print(npArray.dtype) # para elementos del array

3
3
(3, 4)
<class 'list'>
int64

### Acceso y recorrido

In [13]:
print(list2D)

for i in list2D: # array bidimensional
    for j in i:
        print(j)

listD_duplicado = [i*2 for i in list2D]   # forma compacta 
print(listD_duplicado)
        
# El acceso a un elemento específico se realiza por su posición:
print('Fila 0)', list2D[0]) # acceder al primer elemento de la lista

print('Elemento 0 de la fila 0)', list2D[0][0])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 10, 11]]
1
2
3
4
5
6
7
8
9
0
10
11
[[1, 2, 3, 4, 1, 2, 3, 4], [5, 6, 7, 8, 5, 6, 7, 8], [9, 0, 10, 11, 9, 0, 10, 11]]
Fila 0) [1, 2, 3, 4]
Elemento 0 de la fila 0) 1

## 2. Series

Una <b>Serie</b> es un vector que puede contener cualquier tipo de datos (integer, string, float, Python object, etc.). Las etiquetas de los ejes se denominan colectivamente ``índice``.


> s = pd.Series(data, index=index)

<b>data</b> puede ser:

- un valor escalar
- una lista o un ndarray
- un diccionario python


<b> El accesso a elementos de una serie se puede realizar a través de dos métodos:</b>

- Por su posición
- Por su índice

#### Creación de series:

<b>a. Creación de una serie a partir de un tipo de dato simple</b>

In [8]:
# To create:
s = pd.Series('a'); print('letter as series', s)  # from a str (object)

print(type(s))  # <class 'pandas.core.series.Series'>

letter as series 0    a
dtype: object
<class 'pandas.core.series.Series'>

In [9]:
s = pd.Series(5); print('\nnumber as series', s) # from a number
# To access:

print('\n---------ACCESS-----------')
print('\nAccess to the content:', s[0])
print('\nAccess to the content and convert into a serie:', s[[0]])  # Acceder al contenido y convertir en serie

number as series 0    5
dtype: int64

---------ACCESS-----------

Access to the content: 5

Access to the content and convert into a serie: 0    5
dtype: int64

<b> b. Creación de una serie a partir de una lista o array</b>

In [14]:
data = list(range(1,6))  # [1, 2, 3, 4, 5]
data

[1, 2, 3, 4, 5]

In [15]:
# Sin especificar índice, éste inicia desde 0
s = pd.Series(data) ; print('Índices por defecto\n', s)

# Acceso por su posición:
print('\nSegundo elemento: ', s[1])

print('\nPrimeros dos elementos: ', s[:2])

print('\nRango de elementos (slice): ', s[1:3])

Índices por defecto
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Segundo elemento:  2

Primeros dos elementos:  0    1
1    2
dtype: int64

Rango de elementos (slice):  1    2
2    3
dtype: int64

In [12]:
# Especificando un índice
index=['a', 'e', 'i', 'o', 'u']
s = pd.Series(data, index=index) ; print('Índices pre-asignados\n', s)

# s = pd.Series(np.array(data), index=index)  # from array

# Acceso mediante su índice o posición:
print('\nSegundo elemento: ', s['e'], ' por su posición: ', s[1])

Índices pre-asignados
 a    1
e    2
i    3
o    4
u    5
dtype: int64

Segundo elemento:  2  por su posición:  2

In [13]:
s = pd.Series(np.random.randn(5), index=index); s

a    0.481017
e   -0.640810
i    0.498014
o   -1.138109
u    0.202907
dtype: float64

<b>c. Creación de una serie a partir de un diccionario</b>

In [14]:
vacunaDict = {'Asia': 'Israel', 'Sur América': 'Chile'}

In [15]:
vacunaSerie = pd.Series(vacunaDict); vacunaSerie
print(vacunaSerie['Sur América']) # acceso por el índice
vacunaSerie[1] # acceso por la posición

Chile

'Chile'

## 3. Diccionarios

In [16]:
# Declaración de un empleado
employee1 = {
'name': 'María',
'city': 'Loja',
'age': '26',
'gender': 'M',
'roles':['data analyst', 'master student']
}

In [17]:
# Acceso a claves un diccionario:
keys = employee1.keys()
print('Keys: \n', keys)

# Acceso a valores de un diccionario:
valuesE = employee1.values()
print('\nValues: \n', valuesE)

# Acceso a un valor específico, por ejemplo, el nombre:
print('Forma1:', employee1["name"], '\tForma2:', employee1.get("name"))

print('\nData:')

# Print all key names and values in the dictionary, one by one
for key in employee1:
    value = employee1[key] 
    print('\t',key, value)

Keys:
 dict_keys(['name', 'city', 'age', 'gender', 'roles'])

Values:
 dict_values(['María', 'Loja', '26', 'M', ['data analyst', 'master student']])
Forma1: María 	Forma2: María

Data:
	 name María
	 city Loja
	 age 26
	 gender M
	 roles ['data analyst', 'master student']

## 4. Estructuras anidadas

In [16]:
#Lista de estudiantes:
estudiantes = [{
               "cédula":"1105742261",
               "nombres":"Jose Vasquez",
               "edad":"20",
               "carrera":"arquitectura",
               "asignaturas":{
                   "dibujo":7,
                   "moldeado":8.5
               },
               "promedio":7.75
               },
              {
               "cédula":"1103385914",
               "nombres":"Enith Calva",
               "edad":"21",
               "carrera":"computacion",
               "asignaturas":{
                   "programacion":7.5,
                   "base de datos":9
               },
               "promedio":8.25
               }
]; print(estudiantes)

[{'cédula': '1105742261', 'nombres': 'Jose Vasquez', 'edad': '20', 'carrera': 'arquitectura', 'asignaturas': {'dibujo': 7, 'moldeado': 8.5}, 'promedio': 7.75}, {'cédula': '1103385914', 'nombres': 'Enith Calva', 'edad': '21', 'carrera': 'computacion', 'asignaturas': {'programacion': 7.5, 'base de datos': 9}, 'promedio': 8.25}]

In [17]:
# Recorrido de una lista de diccionarios:
print('Longitud de la lista:', len(estudiantes),
      '. Cada componente de la lista es un diccionario.\n')
print('Claves de cada elemento de la lista (diccionario):\n\t',
      estudiantes[0].keys(), '\n')

print('\nObtención de datos, forma 1:')

#Forma 1: un solo ciclo repetitivo:
for e in estudiantes:
    #Imprimir solo valores:
    print(5*'-',e.get('cédula'), e['nombres'], e['edad'],
          e['carrera'], e['asignaturas'], e['promedio'])

print('\nObtención de datos, forma 2:')
#Forma 2: dos ciclos:
for e in estudiantes:
    #Imprimir solo valores:
    for k in e:
        if not(isinstance(e[k], dict)):
            print(5*'-','(',k, ':', e[k], ')')
        else:
            print(5*'-','(',k, ':', ', '.join(e[k]), ')')

Longitud de la lista: 2 . Cada componente de la lista es un diccionario.

Claves de cada elemento de la lista (diccionario):
	 dict_keys(['cédula', 'nombres', 'edad', 'carrera', 'asignaturas', 'promedio'])


Obtención de datos, forma 1:
----- 1105742261 Jose Vasquez 20 arquitectura {'dibujo': 7, 'moldeado': 8.5} 7.75
----- 1103385914 Enith Calva 21 computacion {'programacion': 7.5, 'base de datos': 9} 8.25

Obtención de datos, forma 2:
----- ( cédula : 1105742261 )
----- ( nombres : Jose Vasquez )
----- ( edad : 20 )
----- ( carrera : arquitectura )
----- ( asignaturas : dibujo, moldeado )
----- ( promedio : 7.75 )
----- ( cédula : 1103385914 )
----- ( nombres : Enith Calva )
----- ( edad : 21 )
----- ( carrera : computacion )
----- ( asignaturas : programacion, base de datos )
----- ( promedio : 8.25 )

## 5. DataFrames

### Creación

- Creación desde un diccionario:

In [18]:
student1 = {
    "studentID": '123',
    "grades": {'FDA': 7.5, 'POO': 8.1},
    }
df1 = pd.DataFrame(student1);

# Inspección mediante head (primeros 5 filas) y tail (últimas 5 filas):
df1.head()

    studentID  grades
FDA       123     7.5
POO       123     8.1

In [19]:
# acceder a la primera fila:

print(df1.loc['FDA']) # acceder al contenido de toda la fila a través del nombre de la fila

print('\n', df1.iloc[0])  # acceder a través de la posición

studentID    123
grades       7.5
Name: FDA, dtype: object

 studentID    123
grades       7.5
Name: FDA, dtype: object

In [20]:
# accceder a una columna específica:
print('\n')
print(df1['studentID']) #acceder a una columna específica, como serie
print(df1[['studentID']]) #acceder a una columna específica, como dataframe

FDA    123
POO    123
Name: studentID, dtype: object
    studentID
FDA       123
POO       123

In [21]:
# acceder a un elemento específico

df1.loc['FDA']['grades']

7.5

In [22]:
# Tipos de datos del dataframe
df1.dtypes

studentID     object
grades       float64
dtype: object

In [23]:
df1.columns

Index(['studentID', 'grades'], dtype='object')

In [31]:
# Un atributo de un dataframe se extrae como Series:
for c in df1.columns:
    print(c, type(df1[c]))

print(40*"_")
# Tipo de dato específico del primer elemento de cada serie:
for c in df1.columns:
    print(c, type(df1[c].iloc[0]))

studentID <class 'pandas.core.series.Series'>
grades <class 'pandas.core.series.Series'>
________________________________________
studentID <class 'str'>
grades <class 'numpy.float64'>

### Creación desde un archivo csv

In [35]:
# Crear desde un csv:
data = pd.read_csv('ChurnData.csv', sep=','); data.sample(10)

# También se puede utilizar read_table para cualquier archivo basado en texto:
#data = pd.read_table('ChurnData.csv', sep=',')

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
151,14.0,40.0,13.0,398.0,5.0,11.0,1.0,1.0,1.0,6.40,...,1.0,1.0,1.0,1.0,1.0,1.856,2.890,5.986,4.0,1.0
36,39.0,24.0,2.0,26.0,2.0,4.0,0.0,1.0,0.0,10.40,...,0.0,0.0,0.0,0.0,1.0,2.342,3.240,3.258,1.0,1.0
185,34.0,40.0,21.0,23.0,4.0,9.0,1.0,1.0,1.0,5.95,...,1.0,1.0,1.0,1.0,1.0,1.783,3.248,3.135,4.0,0.0
124,59.0,55.0,29.0,42.0,3.0,21.0,0.0,1.0,0.0,8.95,...,0.0,0.0,0.0,0.0,0.0,2.192,3.240,3.738,2.0,0.0
153,59.0,32.0,9.0,73.0,4.0,5.0,0.0,1.0,0.0,29.20,...,0.0,0.0,1.0,0.0,1.0,3.374,3.068,4.290,2.0,1.0
197,6.0,32.0,10.0,47.0,1.0,10.0,0.0,1.0,0.0,3.85,...,0.0,0.0,1.0,1.0,0.0,1.348,3.168,3.850,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
157,17.0,19.0,0.0,18.0,2.0,0.0,1.0,0.0,0.0,7.10,...,0.0,1.0,0.0,0.0,1.0,1.960,3.240,2.890,2.0,1.0
19,12.0,24.0,2.0,19.0,1.0,0.0,0.0,1.0,0.0,4.00,...,0.0,0.0,1.0,1.0,0.0,1.386,3.209,2.944,3.0,1.0
80,52.0,62.0,23.0,36.0,4.0,17.0,0.0,1.0,0.0,13.35,...,0.0,0.0,0.0,1.0,0.0,2.592,2.918,3.584,1.0,0.0

### Acceso y filtrado de datos:

In [37]:
# Acceder a las filas 4 y 5
print(data[4:6])

# Acceder a una columna específica:
data['age']

   tenure   age  address  income   ed  employ  equip  callcard  wireless  \
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0
5    68.0  52.0     17.0   120.0  1.0    24.0    0.0       1.0       0.0

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
4      7.1  ...    0.0       0.0       1.0     1.0    0.0     1.96    3.091
5     20.7  ...    0.0       0.0       0.0     0.0    0.0     3.03    3.240

   lninc  custcat  churn
4  4.382      3.0    0.0
5  4.787      1.0    0.0

[2 rows x 28 columns]

0      33.0
1      33.0
2      30.0
3      35.0
4      35.0
       ...
195    44.0
196    23.0
197    32.0
198    30.0
199    50.0
Name: age, Length: 200, dtype: float64

In [38]:
# Acceder a filas y columnas específicas:
data.loc[2:5, ['age', 'income']]

    age  income
2  30.0    30.0
3  35.0    76.0
4  35.0    80.0
5  52.0   120.0

In [39]:
data.iloc[2]['age']

30.0

In [41]:
# Seleccionar las filas que cumplan cierta condición:

data[data['churn'] == 0.0].head() #clientes que han desertado

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0
5,68.0,52.0,17.0,120.0,1.0,24.0,0.0,1.0,0.0,20.70,...,0.0,0.0,0.0,0.0,0.0,3.030,3.240,4.787,1.0,0.0
6,42.0,40.0,7.0,37.0,2.0,8.0,1.0,1.0,1.0,8.25,...,0.0,1.0,1.0,1.0,1.0,2.110,3.157,3.611,4.0,0.0

In [45]:
# Presentar lista de clientes con income de 30 y 40:

data[data.income.isin([30, 40])]

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.3,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
40,21.0,29.0,7.0,40.0,4.0,2.0,1.0,1.0,1.0,4.5,...,0.0,1.0,1.0,0.0,0.0,1.504,2.833,3.689,1.0,0.0

In [47]:
# Filtrar dataframes según ciertas condiciones:

#Opción 1:
f1 = data[(data['churn'] == 1.0) & (data['age'] <= 30)]  # Clientes que desertaron, menores a 30 años

#Opción 2:
f2 = data.query("churn == 1.0 & age <= 30")  # Clientes que desertaron, menores a 30 años
f2.tail(3)

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
159,10.0,20.0,1.0,20.0,2.0,0.0,0.0,0.0,0.0,5.90,...,0.0,0.0,0.0,0.0,0.0,1.775,3.240,2.996,1.0,1.0
171,59.0,26.0,3.0,41.0,4.0,1.0,1.0,1.0,1.0,12.65,...,0.0,1.0,0.0,0.0,0.0,2.538,3.240,3.714,2.0,1.0
198,24.0,30.0,0.0,25.0,4.0,5.0,0.0,1.0,1.0,8.70,...,1.0,1.0,1.0,1.0,1.0,2.163,3.866,3.219,4.0,1.0

In [56]:
np.mean(data['income']) # promedio de ingresos de los empleados

75.13

In [54]:
# Clientes que ganan menos del promedio :

data[data['income'] < np.mean(data['income'])].loc[:, ['age', 'income']]

      age  income
1    33.0    33.0
2    30.0    30.0
6    40.0    37.0
7    21.0    17.0
9    51.0    63.0
..    ...     ...
191  20.0    25.0
194  60.0    14.0
196  23.0    24.0
197  32.0    47.0
198  30.0    25.0

[142 rows x 2 columns]

In [57]:
# Ordenar por varios atributos en orden descendente:

data.sort_values(['age', 'income'], ascending = False) # inplace=True para que se ordene el mismo objeto y no se cree una copia

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
66,37.0,76.0,38.0,117.0,4.0,21.0,0.0,1.0,0.0,7.50,...,0.0,0.0,0.0,0.0,0.0,2.015,3.240,4.762,1.0,0.0
98,62.0,76.0,20.0,35.0,3.0,18.0,0.0,1.0,0.0,17.25,...,0.0,0.0,0.0,0.0,1.0,2.848,3.240,3.555,2.0,0.0
130,72.0,75.0,37.0,33.0,1.0,44.0,0.0,1.0,0.0,49.30,...,0.0,0.0,0.0,1.0,0.0,3.898,3.458,3.497,2.0,0.0
125,72.0,75.0,48.0,14.0,2.0,6.0,0.0,1.0,0.0,37.30,...,0.0,0.0,0.0,0.0,0.0,3.619,3.240,2.639,2.0,0.0
34,18.0,69.0,11.0,58.0,3.0,8.0,1.0,1.0,1.0,6.35,...,1.0,1.0,1.0,1.0,1.0,1.848,3.305,4.060,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,1.0,21.0,1.0,18.0,3.0,0.0,1.0,0.0,0.0,2.70,...,0.0,1.0,0.0,1.0,1.0,0.993,3.240,2.890,1.0,1.0
7,9.0,21.0,1.0,17.0,2.0,2.0,0.0,0.0,0.0,2.90,...,0.0,0.0,0.0,0.0,0.0,1.065,3.240,2.833,1.0,0.0
191,6.0,20.0,0.0,25.0,2.0,0.0,0.0,1.0,0.0,1.90,...,0.0,0.0,1.0,1.0,0.0,0.642,3.033,3.219,3.0,0.0
159,10.0,20.0,1.0,20.0,2.0,0.0,0.0,0.0,0.0,5.90,...,0.0,0.0,0.0,0.0,0.0,1.775,3.240,2.996,1.0,1.0
157,17.0,19.0,0.0,18.0,2.0,0.0,1.0,0.0,0.0,7.10,...,0.0,1.0,0.0,0.0,1.0,1.960,3.240,2.890,2.0,1.0