<div style="width: 40%; clear: both;">
<div style="float: left; width: 20%;">
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f7/Universidad_T%C3%A9cnica_Patricular_de_Loja.png", align="left" width="280" height="120">
</div>
</div>
<div style="float: right; width: 70%;">
<p style="margin: 0; padding-top: 32px; text-align:right; color:#003366; font-size:16px"><u>Análisis de datos y visualización</u></p>
<p style="margin: 0; text-align:right; color:#999999; font-size:17px">Redes y Analítica de Datos</p>
</div>
</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>


# Estructuras de datos: arrays, diccionarios, series y dataframes

## Carga de librerías base

In [2]:
import numpy as np
import pandas as pd

## 1. Creación de arrays con Numpy

In [3]:
# Creación de array de una dimensión desde lista:
list1D = [3, 2, 5, 8, 4, 9, 7]
print(type(list1D), list1D)

npArray = np.array(list1D)
print(type(npArray), npArray)

# Creación directa
print(np.array([1, 0, 0, 1], dtype=bool))

<class 'list'> [3, 2, 5, 8, 4, 9, 7]
<class 'numpy.ndarray'> [3 2 5 8 4 9 7]
[ True False False  True]

In [4]:
#Creación de array de 2 dimensiones desde lista:

list2D = [[1,2,3,4],
        [5,6,7,8], 
        [9,0,10,11]]

npArray = np.array(list2D)

print(type(npArray), npArray)

<class 'numpy.ndarray'> [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0 10 11]]

### Diferencias entre objetos de tipo list y array
    
- Una lista puede contener diferentes datos de diferentes tipos.
- Un array de numpy solo puede contener datos del misto tipo.
    
Cuando enviamos diferentes tipos de datos ocurre una conversión automática.

In [5]:
# Conversión automática de tipos de datos:
listD = [1, 'casa', True, 1.5]
arrayD = np.array(listD); print(arrayD)

listD = [1, 7.8, True ,1.5]
arrayD = np.array(listD); print(arrayD)

['1' 'casa' 'True' '1.5']
[1.  7.8 1.  1.5]

### Funciones para crear arrays desde 0

In [6]:
print(np.zeros(10)) # array de 10 ceros.

print(np.random.random(10)) # array de números aleatorios

print(np.arange(10)) # array de los primeros 10 números, incluído el 0

# Para crear arreglos de más de una dimensión se deben enviar las dimensiones:
print(np.zeros((3, 2))) # array de ceros de dimensión 3x2.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.97358939 0.51523054 0.80579184 0.8676212  0.70401516 0.77389543
 0.76754393 0.3547154  0.74589414 0.06943848]
[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]]

### Dimensión y tipos de datos

In [7]:
print(len(list2D)) # lista

print(len(npArray)) # arreglo

print(npArray.shape) # arreglo de dos dimensiones

# Tipos de datos:

print(type(list2D)) # para lista
print(npArray.dtype) # para elementos del array

3
3
(3, 4)
<class 'list'>
int64

### Acceso y recorrido

In [8]:
print(list2D)

for i in list2D: # array bidimensional
    for j in i:
        print(j)

listD_duplicado = [i*2 for i in list2D]   # forma compacta 
print(listD_duplicado)
        
# El acceso a un elemento específico se realiza por su posición:
print('Fila 0)', list2D[0]) # acceder al primer elemento de la lista

print('Elemento 0 de la fila 0)', list2D[0][0])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 0, 10, 11]]
1
2
3
4
5
6
7
8
9
0
10
11
[[1, 2, 3, 4, 1, 2, 3, 4], [5, 6, 7, 8, 5, 6, 7, 8], [9, 0, 10, 11, 9, 0, 10, 11]]
Fila 0) [1, 2, 3, 4]
Elemento 0 de la fila 0) 1

## 2. Series

Una <b>Serie</b> es un vector que puede contener cualquier tipo de datos (integer, string, float, Python object, etc.). Las etiquetas de los ejes se denominan colectivamente ``índice``.


> s = pd.Series(data, index=index)

<b>data</b> puede ser:

- un valor escalar
- una lista o un ndarray
- un diccionario python


<b> El accesso a elementos de una serie se puede realizar a través de dos métodos:</b>

- Por su posición
- Por su índice

#### Creación de series:

<b>a. Creación de una serie a partir de un tipo de dato simple</b>

In [9]:
# To create:
s = pd.Series('a'); print('letter as series', s)  # from a str (object)

print(type(s))  # <class 'pandas.core.series.Series'>

letter as series 0    a
dtype: object
<class 'pandas.core.series.Series'>

In [10]:
s = pd.Series(5); print('\nnumber as series', s) # from a number
# To access:

print('\n---------ACCESS-----------')
print('\nAccess to the content:', s[0])
print('\nAccess to the content and convert into a serie:', s[[0]])  # Acceder al contenido y convertir en serie

number as series 0    5
dtype: int64

---------ACCESS-----------

Access to the content: 5

Access to the content and convert into a serie: 0    5
dtype: int64

<b> b. Creación de una serie a partir de una lista o array</b>

In [11]:
data = list(range(1,6))  # [1, 2, 3, 4, 5]
data

[1, 2, 3, 4, 5]

In [12]:
# Sin especificar índice, éste inicia desde 0
s = pd.Series(data) ; print('Índices por defecto\n', s)

# Acceso por su posición:
print('\nSegundo elemento: ', s[1])

print('\nPrimeros dos elementos: ', s[:2])

print('\nRango de elementos (slice): ', s[1:3])

Índices por defecto
 0    1
1    2
2    3
3    4
4    5
dtype: int64

Segundo elemento:  2

Primeros dos elementos:  0    1
1    2
dtype: int64

Rango de elementos (slice):  1    2
2    3
dtype: int64

In [13]:
# Especificando un índice
index=['a', 'e', 'i', 'o', 'u']
s = pd.Series(data, index=index) ; print('Índices pre-asignados\n', s)

# s = pd.Series(np.array(data), index=index)  # from array

# Acceso mediante su índice o posición:
print('\nSegundo elemento: ', s['e'], ' por su posición: ', s[1])

Índices pre-asignados
 a    1
e    2
i    3
o    4
u    5
dtype: int64

Segundo elemento:  2  por su posición:  2

/var/folders/ns/vbt91tp10ml3rg7kw2y3vdy00000gn/T/ipykernel_4167/3480083622.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print('\nSegundo elemento: ', s['e'], ' por su posición: ', s[1])

In [14]:
s = pd.Series(np.random.randn(5), index=index); s

a   -0.792075
e    0.466496
i   -0.482104
o   -0.041928
u   -1.489462
dtype: float64

<b>c. Creación de una serie a partir de un diccionario</b>

In [15]:
vacunaDict = {'Asia': 'Israel', 'Sur América': 'Chile'}

In [16]:
vacunaSerie = pd.Series(vacunaDict); vacunaSerie
print(vacunaSerie['Sur América']) # acceso por el índice
vacunaSerie[1] # acceso por la posición

Chile

/var/folders/ns/vbt91tp10ml3rg7kw2y3vdy00000gn/T/ipykernel_4167/265717635.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  vacunaSerie[1] # acceso por la posición

'Chile'

## 3. Diccionarios

In [17]:
# Declaración de un empleado
data = {
'protocol': 'HTTP',
'port': '8080',
'bytes': '900'
}

In [18]:
# Acceso a claves un diccionario:
keys = data.keys()
print('Keys: \n', keys)

# Acceso a valores de un diccionario:
valuesE = data.values()
print('\nValues: \n', valuesE)

# Acceso a un valor específico, por ejemplo, el nombre:
print('Forma1:', data["protocol"], '\tForma2:', data.get("protocol"))

print('\nData:')

# Print all key names and values in the dictionary, one by one
for key in data:
    value = data[key] 
    print('\t',key, value)

Keys:
 dict_keys(['protocol', 'port', 'bytes'])

Values:
 dict_values(['HTTP', '8080', '900'])
Forma1: HTTP 	Forma2: HTTP

Data:
	 protocol HTTP
	 port 8080
	 bytes 900

## 4. Estructuras anidadas

In [19]:
#Lista de estudiantes:
estudiantes = [{
               "cédula":"1105742261",
               "nombres":"Jose Vasquez",
               "edad":"20",
               "carrera":"arquitectura",
               "asignaturas":{
                   "dibujo":7,
                   "moldeado":8.5
               },
               "promedio":7.75
               },
              {
               "cédula":"1103385914",
               "nombres":"Enith Calva",
               "edad":"21",
               "carrera":"computacion",
               "asignaturas":{
                   "programacion":7.5,
                   "base de datos":9
               },
               "promedio":8.25
               }
]; print(estudiantes)

[{'cédula': '1105742261', 'nombres': 'Jose Vasquez', 'edad': '20', 'carrera': 'arquitectura', 'asignaturas': {'dibujo': 7, 'moldeado': 8.5}, 'promedio': 7.75}, {'cédula': '1103385914', 'nombres': 'Enith Calva', 'edad': '21', 'carrera': 'computacion', 'asignaturas': {'programacion': 7.5, 'base de datos': 9}, 'promedio': 8.25}]

In [20]:
# Recorrido de una lista de diccionarios:
print('Longitud de la lista:', len(estudiantes),
      '. Cada componente de la lista es un diccionario.\n')
print('Claves de cada elemento de la lista (diccionario):\n\t',
      estudiantes[0].keys(), '\n')

print('\nObtención de datos, forma 1:')

#Forma 1: un solo ciclo repetitivo:
for e in estudiantes:
    #Imprimir solo valores:
    print(5*'-',e.get('cédula'), e['nombres'], e['edad'],
          e['carrera'], e['asignaturas'], e['promedio'])

print('\nObtención de datos, forma 2:')
#Forma 2: dos ciclos:
for e in estudiantes:
    #Imprimir solo valores:
    for k in e:
        if not(isinstance(e[k], dict)):
            print(5*'-','(',k, ':', e[k], ')')
        else:
            print(5*'-','(',k, ':', ', '.join(e[k]), ')')

Longitud de la lista: 2 . Cada componente de la lista es un diccionario.

Claves de cada elemento de la lista (diccionario):
	 dict_keys(['cédula', 'nombres', 'edad', 'carrera', 'asignaturas', 'promedio'])


Obtención de datos, forma 1:
----- 1105742261 Jose Vasquez 20 arquitectura {'dibujo': 7, 'moldeado': 8.5} 7.75
----- 1103385914 Enith Calva 21 computacion {'programacion': 7.5, 'base de datos': 9} 8.25

Obtención de datos, forma 2:
----- ( cédula : 1105742261 )
----- ( nombres : Jose Vasquez )
----- ( edad : 20 )
----- ( carrera : arquitectura )
----- ( asignaturas : dibujo, moldeado )
----- ( promedio : 7.75 )
----- ( cédula : 1103385914 )
----- ( nombres : Enith Calva )
----- ( edad : 21 )
----- ( carrera : computacion )
----- ( asignaturas : programacion, base de datos )
----- ( promedio : 8.25 )

## 5. DataFrames

### Creación

- Creación desde un diccionario:

In [37]:
import pandas as pd

# 1. Crear el DataFrame a partir de un diccionario (cada clave = una columna)
datos = {
    "dispositivo":  ["RT-01", "SW-01", "SW-02", "AP-01", "AP-02", "RT-02"],
    "tipo":         ["router", "switch", "switch", "access_point", "access_point", "router"],
    "ciudad":       ["Loja", "Loja", "Quito", "Loja", "Quito", "Quito"],
    "latencia_ms":  [18.4, 9.8, 12.1, 42.7, 27.5, 21.0],
    "trafico_mbps": [850, 420, 380, 95, 120, 910],
    "activo":       [True, True, True, False, True, True],
}
df = pd.DataFrame(datos)


- Explorar la estructura

In [38]:
df                 # tabla completa
df.shape           # (6, 6) -> (filas, columnas)
df.dtypes          # texto, float64, int64, bool
df.head(3)         # primeras 3 filas

  dispositivo    tipo ciudad  latencia_ms  trafico_mbps  activo
0       RT-01  router   Loja         18.4           850    True
1       SW-01  switch   Loja          9.8           420    True
2       SW-02  switch  Quito         12.1           380    True

In [39]:
df.tail(3)         # últimas 3 filas

  dispositivo          tipo ciudad  latencia_ms  trafico_mbps  activo
3       AP-01  access_point   Loja         42.7            95   False
4       AP-02  access_point  Quito         27.5           120    True
5       RT-02        router  Quito         21.0           910    True

In [40]:
df.sample(2)         # 2 filas aleatorias del dataframe

  dispositivo    tipo ciudad  latencia_ms  trafico_mbps  activo
2       SW-02  switch  Quito         12.1           380    True
5       RT-02  router  Quito         21.0           910    True

-  Seleccionar columnas y filas

In [43]:
print(df["latencia_ms"])                                          # una columna (Series)
df[["dispositivo", "ciudad"]]                              # varias columnas (DataFrame)

0    18.4
1     9.8
2    12.1
3    42.7
4    27.5
5    21.0
Name: latencia_ms, dtype: float64

  dispositivo ciudad
0       RT-01   Loja
1       SW-01   Loja
2       SW-02  Quito
3       AP-01   Loja
4       AP-02  Quito
5       RT-02  Quito

In [44]:
df.loc[0]                                                  # una fila por su índice
df.loc[df["ciudad"] == "Loja", ["dispositivo", "latencia_ms"]]   # filas y columnas a la vez

  dispositivo  latencia_ms
0       RT-01         18.4
1       SW-01          9.8
3       AP-01         42.7

In [47]:
# acceder a un elemento específico
df.loc[1]['latencia_ms']

9.8

- Estructura y tipos de datos del dataframe

In [55]:
df.columns # nombres de columnas

Index(['dispositivo', 'tipo', 'ciudad', 'latencia_ms', 'trafico_mbps',
       'activo'],
      dtype='object')

In [54]:
df.info() # presenta la estructura y los tipos de datos de las Series

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   dispositivo   6 non-null      object
 1   tipo          6 non-null      object
 2   ciudad        6 non-null      object
 3   latencia_ms   6 non-null      float64
 4   trafico_mbps  6 non-null      int64
 5   activo        6 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 374.0+ bytes

In [49]:
df.dtypes

dispositivo      object
tipo             object
ciudad           object
latencia_ms     float64
trafico_mbps      int64
activo             bool
dtype: object

#### Tamaño

In [51]:
df.shape # número de filas vs. número de columnas

(6, 6)

In [52]:
len(df) # número de filas

6

- Resumen estadístico

In [57]:
df.describe() # resumen estadístico de variables numéricas.

       latencia_ms  trafico_mbps
count     6.000000      6.000000
mean     21.916667    462.500000
std      11.995902    349.681998
min       9.800000     95.000000
25%      13.675000    185.000000
50%      19.700000    400.000000
75%      25.875000    742.500000
max      42.700000    910.000000